PUSH=lab2.Operations.PushOperation
POP=lab2.Operations.PopOperation
PRINT=lab2.Operations.PrintOperation
DEFINE=lab2.Operations.DefineOperation
+=lab2.Operations.PlusOperation
-=lab2.Operations.MinusOperation
*=lab2.Operations.MultiplyOperation
/=lab2.Operations.DivideOperation
SQRT=lab2.Operations.SqrtOperation