PUSH=stackCalculator.Operations.PushOperation
POP=stackCalculator.Operations.PopOperation
PRINT=stackCalculator.Operations.PrintOperation
DEFINE=stackCalculator.Operations.DefineOperation
+=stackCalculator.Operations.PlusOperation
-=stackCalculator.Operations.MinusOperation
*=stackCalculator.Operations.MultiplyOperation
/=stackCalculator.Operations.DivideOperation
SQRT=stackCalculator.Operations.SqrtOperation